---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foodapp
  labels:
    app: foodapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foodapp
  # pod spec begins here
  template:
    metadata:
      labels:
        app: foodapp
    spec:
      containers:
        - name: foodapp
          image: registry.digitalocean.com/flask-registry/shavitzc/app:latest 
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
